// megafunction wizard: %RAM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: ram_gr.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 9.0 Build 235 06/17/2009 SP 2 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2009 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altsyncram CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone II" ENABLE_RUNTIME_MOD="YES" INIT_FILE="memor.mif" INSTANCE_NAME="RAM1" NUMWORDS_A=128 OPERATION_MODE="SINGLE_PORT" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="UNREGISTERED" POWER_UP_UNINITIALIZED="FALSE" RAM_BLOCK_TYPE="M4K" WIDTH_A=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=7 address_a clock0 data_a q_a wren_a
//VERSION_BEGIN 9.0SP2 cbx_altsyncram 2009:05:19:16:53:16:SJ cbx_cycloneii 2008:05:19:10:57:37:SJ cbx_lpm_add_sub 2009:05:07:10:25:28:SJ cbx_lpm_compare 2009:02:03:01:43:16:SJ cbx_lpm_decode 2008:05:19:10:39:27:SJ cbx_lpm_mux 2009:03:31:01:01:28:SJ cbx_mgl 2009:02:26:16:06:21:SJ cbx_stratix 2008:09:18:16:08:35:SJ cbx_stratixii 2008:11:14:16:08:42:SJ cbx_stratixiii 2009:05:12:13:36:56:SJ cbx_util_mgl 2008:11:21:14:58:47:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//altsyncram ADDRESS_ACLR_B="NONE" ADDRESS_REG_B="CLOCK1" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone II" ENABLE_RUNTIME_MOD="NO" INDATA_ACLR_B="NONE" INDATA_REG_B="CLOCK1" INIT_FILE="memor.mif" NUMWORDS_A=128 NUMWORDS_B=128 OPERATION_MODE="BIDIR_DUAL_PORT" OUTDATA_ACLR_A="NONE" OUTDATA_ACLR_B="NONE" OUTDATA_REG_A="UNREGISTERED" OUTDATA_REG_B="UNREGISTERED" RAM_BLOCK_TYPE="M4K" RDCONTROL_REG_B="CLOCK1" read_during_write_mode_port_a="NEW_DATA_NO_NBE_READ" WIDTH_A=8 WIDTH_B=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=7 WIDTHAD_B=7 WRCONTROL_ACLR_B="NONE" WRCONTROL_WRADDRESS_REG_B="CLOCK1" address_a address_b clock0 clock1 data_a data_b q_a q_b wren_a wren_b
//VERSION_BEGIN 9.0SP2 cbx_altsyncram 2009:05:19:16:53:16:SJ cbx_cycloneii 2008:05:19:10:57:37:SJ cbx_lpm_add_sub 2009:05:07:10:25:28:SJ cbx_lpm_compare 2009:02:03:01:43:16:SJ cbx_lpm_decode 2008:05:19:10:39:27:SJ cbx_lpm_mux 2009:03:31:01:01:28:SJ cbx_mgl 2009:02:26:16:06:21:SJ cbx_stratix 2008:09:18:16:08:35:SJ cbx_stratixii 2008:11:14:16:08:42:SJ cbx_stratixiii 2009:05:12:13:36:56:SJ cbx_util_mgl 2008:11:21:14:58:47:SJ  VERSION_END

//synthesis_resources = M4K 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  ram_gr_altsyncram1
	( 
	address_a,
	address_b,
	clock0,
	clock1,
	data_a,
	data_b,
	q_a,
	q_b,
	wren_a,
	wren_b) /* synthesis synthesis_clearbox=1 */;
	input   [6:0]  address_a;
	input   [6:0]  address_b;
	input   clock0;
	input   clock1;
	input   [7:0]  data_a;
	input   [7:0]  data_b;
	output   [7:0]  q_a;
	output   [7:0]  q_b;
	input   wren_a;
	input   wren_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   [6:0]  address_b;
	tri1   clock0;
	tri1   clock1;
	tri1   [7:0]  data_a;
	tri1   [7:0]  data_b;
	tri0   wren_a;
	tri0   wren_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block3a_0portadataout;
	wire  [0:0]   wire_ram_block3a_1portadataout;
	wire  [0:0]   wire_ram_block3a_2portadataout;
	wire  [0:0]   wire_ram_block3a_3portadataout;
	wire  [0:0]   wire_ram_block3a_4portadataout;
	wire  [0:0]   wire_ram_block3a_5portadataout;
	wire  [0:0]   wire_ram_block3a_6portadataout;
	wire  [0:0]   wire_ram_block3a_7portadataout;
	wire  [0:0]   wire_ram_block3a_0portbdataout;
	wire  [0:0]   wire_ram_block3a_1portbdataout;
	wire  [0:0]   wire_ram_block3a_2portbdataout;
	wire  [0:0]   wire_ram_block3a_3portbdataout;
	wire  [0:0]   wire_ram_block3a_4portbdataout;
	wire  [0:0]   wire_ram_block3a_5portbdataout;
	wire  [0:0]   wire_ram_block3a_6portbdataout;
	wire  [0:0]   wire_ram_block3a_7portbdataout;
	wire  [6:0]  address_a_wire;
	wire  [6:0]  address_b_wire;

	cycloneii_ram_block   ram_block3a_0
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[0]}),
	.portadataout(wire_ram_block3a_0portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[0]}),
	.portbdataout(wire_ram_block3a_0portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_0.connectivity_checking = "OFF",
		ram_block3a_0.init_file = "memor.mif",
		ram_block3a_0.init_file_layout = "port_a",
		ram_block3a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_0.mem_init0 = 128'h08F070B03030D09010E0A020C0408000,
		ram_block3a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_0.operation_mode = "bidir_dual_port",
		ram_block3a_0.port_a_address_width = 7,
		ram_block3a_0.port_a_data_width = 1,
		ram_block3a_0.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_0.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_0.port_a_first_address = 0,
		ram_block3a_0.port_a_first_bit_number = 0,
		ram_block3a_0.port_a_last_address = 127,
		ram_block3a_0.port_a_logical_ram_depth = 128,
		ram_block3a_0.port_a_logical_ram_width = 8,
		ram_block3a_0.port_b_address_clock = "clock1",
		ram_block3a_0.port_b_address_width = 7,
		ram_block3a_0.port_b_data_in_clock = "clock1",
		ram_block3a_0.port_b_data_width = 1,
		ram_block3a_0.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_0.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_0.port_b_first_address = 0,
		ram_block3a_0.port_b_first_bit_number = 0,
		ram_block3a_0.port_b_last_address = 127,
		ram_block3a_0.port_b_logical_ram_depth = 128,
		ram_block3a_0.port_b_logical_ram_width = 8,
		ram_block3a_0.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_0.ram_block_type = "M4K",
		ram_block3a_0.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_1
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[1]}),
	.portadataout(wire_ram_block3a_1portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[1]}),
	.portbdataout(wire_ram_block3a_1portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_1.connectivity_checking = "OFF",
		ram_block3a_1.init_file = "memor.mif",
		ram_block3a_1.init_file_layout = "port_a",
		ram_block3a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_1.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_1.operation_mode = "bidir_dual_port",
		ram_block3a_1.port_a_address_width = 7,
		ram_block3a_1.port_a_data_width = 1,
		ram_block3a_1.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_1.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_1.port_a_first_address = 0,
		ram_block3a_1.port_a_first_bit_number = 1,
		ram_block3a_1.port_a_last_address = 127,
		ram_block3a_1.port_a_logical_ram_depth = 128,
		ram_block3a_1.port_a_logical_ram_width = 8,
		ram_block3a_1.port_b_address_clock = "clock1",
		ram_block3a_1.port_b_address_width = 7,
		ram_block3a_1.port_b_data_in_clock = "clock1",
		ram_block3a_1.port_b_data_width = 1,
		ram_block3a_1.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_1.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_1.port_b_first_address = 0,
		ram_block3a_1.port_b_first_bit_number = 1,
		ram_block3a_1.port_b_last_address = 127,
		ram_block3a_1.port_b_logical_ram_depth = 128,
		ram_block3a_1.port_b_logical_ram_width = 8,
		ram_block3a_1.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_1.ram_block_type = "M4K",
		ram_block3a_1.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_2
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[2]}),
	.portadataout(wire_ram_block3a_2portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[2]}),
	.portbdataout(wire_ram_block3a_2portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_2.connectivity_checking = "OFF",
		ram_block3a_2.init_file = "memor.mif",
		ram_block3a_2.init_file_layout = "port_a",
		ram_block3a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_2.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_2.operation_mode = "bidir_dual_port",
		ram_block3a_2.port_a_address_width = 7,
		ram_block3a_2.port_a_data_width = 1,
		ram_block3a_2.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_2.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_2.port_a_first_address = 0,
		ram_block3a_2.port_a_first_bit_number = 2,
		ram_block3a_2.port_a_last_address = 127,
		ram_block3a_2.port_a_logical_ram_depth = 128,
		ram_block3a_2.port_a_logical_ram_width = 8,
		ram_block3a_2.port_b_address_clock = "clock1",
		ram_block3a_2.port_b_address_width = 7,
		ram_block3a_2.port_b_data_in_clock = "clock1",
		ram_block3a_2.port_b_data_width = 1,
		ram_block3a_2.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_2.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_2.port_b_first_address = 0,
		ram_block3a_2.port_b_first_bit_number = 2,
		ram_block3a_2.port_b_last_address = 127,
		ram_block3a_2.port_b_logical_ram_depth = 128,
		ram_block3a_2.port_b_logical_ram_width = 8,
		ram_block3a_2.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_2.ram_block_type = "M4K",
		ram_block3a_2.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_3
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[3]}),
	.portadataout(wire_ram_block3a_3portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[3]}),
	.portbdataout(wire_ram_block3a_3portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_3.connectivity_checking = "OFF",
		ram_block3a_3.init_file = "memor.mif",
		ram_block3a_3.init_file_layout = "port_a",
		ram_block3a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_3.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_3.operation_mode = "bidir_dual_port",
		ram_block3a_3.port_a_address_width = 7,
		ram_block3a_3.port_a_data_width = 1,
		ram_block3a_3.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_3.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_3.port_a_first_address = 0,
		ram_block3a_3.port_a_first_bit_number = 3,
		ram_block3a_3.port_a_last_address = 127,
		ram_block3a_3.port_a_logical_ram_depth = 128,
		ram_block3a_3.port_a_logical_ram_width = 8,
		ram_block3a_3.port_b_address_clock = "clock1",
		ram_block3a_3.port_b_address_width = 7,
		ram_block3a_3.port_b_data_in_clock = "clock1",
		ram_block3a_3.port_b_data_width = 1,
		ram_block3a_3.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_3.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_3.port_b_first_address = 0,
		ram_block3a_3.port_b_first_bit_number = 3,
		ram_block3a_3.port_b_last_address = 127,
		ram_block3a_3.port_b_logical_ram_depth = 128,
		ram_block3a_3.port_b_logical_ram_width = 8,
		ram_block3a_3.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_3.ram_block_type = "M4K",
		ram_block3a_3.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_4
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[4]}),
	.portadataout(wire_ram_block3a_4portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[4]}),
	.portbdataout(wire_ram_block3a_4portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_4.connectivity_checking = "OFF",
		ram_block3a_4.init_file = "memor.mif",
		ram_block3a_4.init_file_layout = "port_a",
		ram_block3a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_4.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_4.operation_mode = "bidir_dual_port",
		ram_block3a_4.port_a_address_width = 7,
		ram_block3a_4.port_a_data_width = 1,
		ram_block3a_4.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_4.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_4.port_a_first_address = 0,
		ram_block3a_4.port_a_first_bit_number = 4,
		ram_block3a_4.port_a_last_address = 127,
		ram_block3a_4.port_a_logical_ram_depth = 128,
		ram_block3a_4.port_a_logical_ram_width = 8,
		ram_block3a_4.port_b_address_clock = "clock1",
		ram_block3a_4.port_b_address_width = 7,
		ram_block3a_4.port_b_data_in_clock = "clock1",
		ram_block3a_4.port_b_data_width = 1,
		ram_block3a_4.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_4.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_4.port_b_first_address = 0,
		ram_block3a_4.port_b_first_bit_number = 4,
		ram_block3a_4.port_b_last_address = 127,
		ram_block3a_4.port_b_logical_ram_depth = 128,
		ram_block3a_4.port_b_logical_ram_width = 8,
		ram_block3a_4.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_4.ram_block_type = "M4K",
		ram_block3a_4.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_5
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[5]}),
	.portadataout(wire_ram_block3a_5portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[5]}),
	.portbdataout(wire_ram_block3a_5portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_5.connectivity_checking = "OFF",
		ram_block3a_5.init_file = "memor.mif",
		ram_block3a_5.init_file_layout = "port_a",
		ram_block3a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_5.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_5.operation_mode = "bidir_dual_port",
		ram_block3a_5.port_a_address_width = 7,
		ram_block3a_5.port_a_data_width = 1,
		ram_block3a_5.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_5.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_5.port_a_first_address = 0,
		ram_block3a_5.port_a_first_bit_number = 5,
		ram_block3a_5.port_a_last_address = 127,
		ram_block3a_5.port_a_logical_ram_depth = 128,
		ram_block3a_5.port_a_logical_ram_width = 8,
		ram_block3a_5.port_b_address_clock = "clock1",
		ram_block3a_5.port_b_address_width = 7,
		ram_block3a_5.port_b_data_in_clock = "clock1",
		ram_block3a_5.port_b_data_width = 1,
		ram_block3a_5.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_5.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_5.port_b_first_address = 0,
		ram_block3a_5.port_b_first_bit_number = 5,
		ram_block3a_5.port_b_last_address = 127,
		ram_block3a_5.port_b_logical_ram_depth = 128,
		ram_block3a_5.port_b_logical_ram_width = 8,
		ram_block3a_5.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_5.ram_block_type = "M4K",
		ram_block3a_5.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_6
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[6]}),
	.portadataout(wire_ram_block3a_6portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[6]}),
	.portbdataout(wire_ram_block3a_6portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_6.connectivity_checking = "OFF",
		ram_block3a_6.init_file = "memor.mif",
		ram_block3a_6.init_file_layout = "port_a",
		ram_block3a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_6.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_6.operation_mode = "bidir_dual_port",
		ram_block3a_6.port_a_address_width = 7,
		ram_block3a_6.port_a_data_width = 1,
		ram_block3a_6.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_6.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_6.port_a_first_address = 0,
		ram_block3a_6.port_a_first_bit_number = 6,
		ram_block3a_6.port_a_last_address = 127,
		ram_block3a_6.port_a_logical_ram_depth = 128,
		ram_block3a_6.port_a_logical_ram_width = 8,
		ram_block3a_6.port_b_address_clock = "clock1",
		ram_block3a_6.port_b_address_width = 7,
		ram_block3a_6.port_b_data_in_clock = "clock1",
		ram_block3a_6.port_b_data_width = 1,
		ram_block3a_6.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_6.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_6.port_b_first_address = 0,
		ram_block3a_6.port_b_first_bit_number = 6,
		ram_block3a_6.port_b_last_address = 127,
		ram_block3a_6.port_b_logical_ram_depth = 128,
		ram_block3a_6.port_b_logical_ram_width = 8,
		ram_block3a_6.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_6.ram_block_type = "M4K",
		ram_block3a_6.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block3a_7
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[7]}),
	.portadataout(wire_ram_block3a_7portadataout[0:0]),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbdatain({data_b[7]}),
	.portbdataout(wire_ram_block3a_7portbdataout[0:0]),
	.portbrewe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_7.connectivity_checking = "OFF",
		ram_block3a_7.init_file = "memor.mif",
		ram_block3a_7.init_file_layout = "port_a",
		ram_block3a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_7.mem_init0 = 128'h00000000000000000000000000000000,
		ram_block3a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_7.operation_mode = "bidir_dual_port",
		ram_block3a_7.port_a_address_width = 7,
		ram_block3a_7.port_a_data_width = 1,
		ram_block3a_7.port_a_disable_ce_on_input_registers = "on",
		ram_block3a_7.port_a_disable_ce_on_output_registers = "on",
		ram_block3a_7.port_a_first_address = 0,
		ram_block3a_7.port_a_first_bit_number = 7,
		ram_block3a_7.port_a_last_address = 127,
		ram_block3a_7.port_a_logical_ram_depth = 128,
		ram_block3a_7.port_a_logical_ram_width = 8,
		ram_block3a_7.port_b_address_clock = "clock1",
		ram_block3a_7.port_b_address_width = 7,
		ram_block3a_7.port_b_data_in_clock = "clock1",
		ram_block3a_7.port_b_data_width = 1,
		ram_block3a_7.port_b_disable_ce_on_input_registers = "on",
		ram_block3a_7.port_b_disable_ce_on_output_registers = "on",
		ram_block3a_7.port_b_first_address = 0,
		ram_block3a_7.port_b_first_bit_number = 7,
		ram_block3a_7.port_b_last_address = 127,
		ram_block3a_7.port_b_logical_ram_depth = 128,
		ram_block3a_7.port_b_logical_ram_width = 8,
		ram_block3a_7.port_b_read_enable_write_enable_clock = "clock1",
		ram_block3a_7.ram_block_type = "M4K",
		ram_block3a_7.lpm_type = "cycloneii_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_a = {wire_ram_block3a_7portadataout[0], wire_ram_block3a_6portadataout[0], wire_ram_block3a_5portadataout[0], wire_ram_block3a_4portadataout[0], wire_ram_block3a_3portadataout[0], wire_ram_block3a_2portadataout[0], wire_ram_block3a_1portadataout[0], wire_ram_block3a_0portadataout[0]},
		q_b = {wire_ram_block3a_7portbdataout[0], wire_ram_block3a_6portbdataout[0], wire_ram_block3a_5portbdataout[0], wire_ram_block3a_4portbdataout[0], wire_ram_block3a_3portbdataout[0], wire_ram_block3a_2portbdataout[0], wire_ram_block3a_1portbdataout[0], wire_ram_block3a_0portbdataout[0]};
endmodule //ram_gr_altsyncram1

//synthesis_resources = M4K 1 sld_mod_ram_rom 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  ram_gr_altsyncram
	( 
	address_a,
	clock0,
	data_a,
	q_a,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   [6:0]  address_a;
	input   clock0;
	input   [7:0]  data_a;
	output   [7:0]  q_a;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
	tri1   [7:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [7:0]   wire_altsyncram1_q_a;
	wire  [7:0]   wire_altsyncram1_q_b;
	wire  [6:0]   wire_mgl_prim2_address;
	wire  [7:0]   wire_mgl_prim2_data_write;
	wire  wire_mgl_prim2_enable_write;
	wire  wire_mgl_prim2_tck_usr;

	ram_gr_altsyncram1   altsyncram1
	( 
	.address_a(address_a),
	.address_b(wire_mgl_prim2_address),
	.clock0(clock0),
	.clock1(wire_mgl_prim2_tck_usr),
	.data_a(data_a),
	.data_b(wire_mgl_prim2_data_write),
	.q_a(wire_altsyncram1_q_a),
	.q_b(wire_altsyncram1_q_b),
	.wren_a(wren_a),
	.wren_b(wire_mgl_prim2_enable_write));
	sld_mod_ram_rom   mgl_prim2
	( 
	.address(wire_mgl_prim2_address),
	.data_read(wire_altsyncram1_q_b),
	.data_write(wire_mgl_prim2_data_write),
	.enable_write(wire_mgl_prim2_enable_write),
	.tck_usr(wire_mgl_prim2_tck_usr));
	defparam
		mgl_prim2.cvalue = 8'h00,
		mgl_prim2.is_data_in_ram = 1,
		mgl_prim2.is_readable = 1,
		mgl_prim2.node_name = 1380011313,
		mgl_prim2.numwords = 128,
		mgl_prim2.shift_count_bits = 4,
		mgl_prim2.width_word = 8,
		mgl_prim2.widthad = 7;
	assign
		q_a = wire_altsyncram1_q_a;
endmodule //ram_gr_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module ram_gr (
	address,
	clock,
	data,
	wren,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[6:0]  address;
	input	  clock;
	input	[7:0]  data;
	input	  wren;
	output	[7:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [7:0] sub_wire0;
	wire [7:0] q = sub_wire0[7:0];

	ram_gr_altsyncram	ram_gr_altsyncram_component (
				.wren_a (wren),
				.clock0 (clock),
				.address_a (address),
				.data_a (data),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrData NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: DataBusSeparated NUMERIC "1"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "1"
// Retrieval info: PRIVATE: JTAG_ID STRING "RAM1"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "memor.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "128"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "2"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_PORT_A NUMERIC "3"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegData NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "1"
// Retrieval info: PRIVATE: WRCONTROL_ACLR_A NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "7"
// Retrieval info: PRIVATE: WidthData NUMERIC "8"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "memor.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=YES,INSTANCE_NAME=RAM1"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "128"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "SINGLE_PORT"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "UNREGISTERED"
// Retrieval info: CONSTANT: POWER_UP_UNINITIALIZED STRING "FALSE"
// Retrieval info: CONSTANT: RAM_BLOCK_TYPE STRING "M4K"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "7"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 7 0 INPUT NODEFVAL address[6..0]
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC clock
// Retrieval info: USED_PORT: data 0 0 8 0 INPUT NODEFVAL data[7..0]
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL q[7..0]
// Retrieval info: USED_PORT: wren 0 0 0 0 INPUT NODEFVAL wren
// Retrieval info: CONNECT: @address_a 0 0 7 0 address 0 0 7 0
// Retrieval info: CONNECT: q 0 0 8 0 @q_a 0 0 8 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @data_a 0 0 8 0 data 0 0 8 0
// Retrieval info: CONNECT: @wren_a 0 0 0 0 wren 0 0 0 0
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr_waveforms.html TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr_wave*.jpg FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram_gr_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
